name: cabueta
on:
  workflow_dispatch:

jobs:
  cabueta:
    uses: gbrls/cabueta/.github/workflows/cabueta.yml@main
    with:
      dast-check: true
      target-url: https://b2bstoreqa.myvtex.com/_v/private
  print:
    runs-on: ubuntu-latest
    needs: cabueta
    steps:
      - name: Print output
        run: echo ${{ needs.cabueta.outputs.report }}
